spring:
  cassandra:
    contact-points: cassandra1:9042, cassandra2:9042, cassandra3:9042
    keyspace-name: finance
    schema-action: create_if_not_exists
    request:
      timeout: 10s
    connection:
      connect-timeout: 10s
      init-query-timeout: 10s
    local-datacenter: datacenter1
    username: cassandra
    password: cassandra
    port: 9042
  application:
    name: finances-query
  cloud:
    function:
      definition:
        financeEntryForMemberUpdatedMessageRouter;
        financeEntryUpdatedMessageRouter;
        bandMemberRemovedMessageRouter;
    stream:
      function:
        bindings:
          financeEntryForMemberUpdatedMessageRouter-in-0: finance-entry-for-member-updated
          financeEntryUpdatedMessageRouter-in-0: finance-entry-updated
          bandMemberRemovedMessageRouter-in-0: band-member-removed
      default:
        group: ${spring.application.name}
        content-type: application/json
      bindings:
        finance-entry-for-member-updated:
          destination: bm.finance.entry.for.member.updated
          consumer:
            batch-mode: true
        finance-entry-updated:
          destination: bm.finance.entry.updated
        band-member-removed:
          destination: bm.band.member.removed
      kafka:
        binder:
          auto-create-topics: true #TODO remove for manual topic creation
          brokers: kafka1:9091,kafka2:9092,kafka3:9093