spring:
  cassandra:
    contact-points: cassandra1:9042, cassandra2:9042, cassandra3:9042
    keyspace-name: band
    schema-action: create_if_not_exists
    request:
      timeout: 10s
    connection:
      connect-timeout: 10s
      init-query-timeout: 10s
    local-datacenter: datacenter1
    username: cassandra
    password: cassandra
    port: 9042
  application:
    name: bands-query
  cloud:
    function:
      definition:
        bandMemberAddedMessageRouter;
        bandMemberRemovedMessageRouter;
        bandDefaultPrivilegesChangedMessageRouter;
        bandMemberPrivilegesChangedMessageRouter;
    stream:
      function:
        bindings:
          bandMemberAddedMessageRouter-in-0: bm.band.member.added
          bandMemberRemovedMessageRouter-in-0: bm.band.member.removed
          bandDefaultPrivilegesChangedMessageRouter-in-0: bm.band.default.privileges.changed
          bandMemberPrivilegesChangedMessageRouter-in-0: bm.band.member.privileges.changed
      default:
        group: ${spring.application.name}
        content-type: application/json
      bindings:
        band-member-added:
          destination: bm.band.member.added
        band-member-removed:
          destination: bm.band.member.removed
        band-member-privileges-changed:
          destination: bm.band.member.privileges.changed
        band-default-privileges-changed:
          destination: bm.band.default.privileges.changed
      kafka:
        binder:
          auto-create-topics: true #TODO remove for manual topic creation
          brokers: kafka1:9091,kafka2:9092,kafka3:9093