spring:
  application:
    name: finances-command
  datasource:
    url: jdbc:postgresql://postgres-db:5432/finances-command-db
    username: sa
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # TODO remove in future
  cloud:
    function:
      definition:
        bandMemberPrivilegesChangedMessageRouter;
        bandMemberRemovedMessageRouter;
    stream:
      function:
        bindings:
          bandMemberPrivilegesChangedMessageRouter-in-0: band-member-privileges-changed
          bandMemberRemovedMessageRouter-in-0: band-member-removed
      default:
        group: ${spring.application.name}
        content-type: application/json
      bindings:
        band-member-privileges-changed:
          destination: bm.band.member.privileges.changed
        band-member-removed:
          destination: bm.band.member.removed
        finance-entry-for-member-updated:
          destination: bm.finance.entry.for.member.updated
          producer:
            partition-key-expression: headers['partitionKey']
        finance-entry-updated:
          destination: bm.finance.entry.updated
          producer:
            partition-key-expression: headers['partitionKey']
      kafka:
        binder:
          auto-create-topics: true #TODO remove for manual topic creation
          brokers: kafka1:9091,kafka2:9092,kafka3:9093
grpc:
  server:
#    security:
#      enabled: false
    port: 8080