spring:
  cassandra:
    contact-points: cassandra1:9042, cassandra2:9042, cassandra3:9042
    keyspace-name: calendar
    schema-action: create_if_not_exists
    request:
      timeout: 10s
    connection:
      connect-timeout: 10s
      init-query-timeout: 10s
    local-datacenter: datacenter1
    username: cassandra
    password: cassandra
    port: 9042
  application:
    name: calendars-query
  cloud:
    function:
      definition:
        bandMemberRemovedMessageRouter;
        calendarEntryMemberEmptyRestrictionCreatedMessageRouter;
        calendarEntryMemberRestrictionChangedMessageRouter;
    stream:
      function:
        bindings:
          bandMemberRemovedMessageRouter-in-0: band-member-removed
          calendarEntryMemberEmptyRestrictionCreatedMessageRouter-in-0: calendar-entry-member-empty-restriction-created
          calendarEntryMemberRestrictionChangedMessageRouter-in-0: calendar-entry-member-restriction-changed
      default:
        group: ${spring.application.name}
        content-type: application/json
      bindings:
        band-member-removed:
          destination: bm.band.member.removed
        calendar-entry-member-empty-restriction-created:
          destination: bm.calendar.entry.member.empty.restriction.created
          consumer:
            batch-mode: true
        calendar-entry-member-restriction-changed:
          destination: bm.calendar.entry.member.restriction.changed
      kafka:
        binder:
          auto-create-topics: true #TODO remove for manual topic creation
          brokers: kafka1:9091,kafka2:9092,kafka3:9093