spring:
  cassandra:
    contact-points: 127.0.0.1
  cloud:
    stream:
      kafka:
        binder:
          auto-create-topics: true
          brokers: localhost:9091,localhost:9092,localhost:9093
server:
  port: 8086
logging:
  level:
    org.springframework.data.cassandra.core.cql.CqlTemplate: DEBUG