// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: finances-command.proto

package com.qsspy.grpc.finances.command;

public interface AddFinanceEntryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AddFinanceEntryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string bandId = 1;</code>
   * @return The bandId.
   */
  java.lang.String getBandId();
  /**
   * <code>string bandId = 1;</code>
   * @return The bytes for bandId.
   */
  com.google.protobuf.ByteString
      getBandIdBytes();

  /**
   * <code>string initiatorsBandId = 2;</code>
   * @return The initiatorsBandId.
   */
  java.lang.String getInitiatorsBandId();
  /**
   * <code>string initiatorsBandId = 2;</code>
   * @return The bytes for initiatorsBandId.
   */
  com.google.protobuf.ByteString
      getInitiatorsBandIdBytes();

  /**
   * <code>string initiatorsEmail = 3;</code>
   * @return The initiatorsEmail.
   */
  java.lang.String getInitiatorsEmail();
  /**
   * <code>string initiatorsEmail = 3;</code>
   * @return The bytes for initiatorsEmail.
   */
  com.google.protobuf.ByteString
      getInitiatorsEmailBytes();

  /**
   * <code>string amount = 4;</code>
   * @return The amount.
   */
  java.lang.String getAmount();
  /**
   * <code>string amount = 4;</code>
   * @return The bytes for amount.
   */
  com.google.protobuf.ByteString
      getAmountBytes();

  /**
   * <code>string description = 5;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 5;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>bool isOutcome = 6;</code>
   * @return The isOutcome.
   */
  boolean getIsOutcome();
}
