// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: finances-command.proto

package com.qsspy.grpc.finances.command;

/**
 * Protobuf type {@code AddFinanceEntryRequest}
 */
public final class AddFinanceEntryRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:AddFinanceEntryRequest)
    AddFinanceEntryRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AddFinanceEntryRequest.newBuilder() to construct.
  private AddFinanceEntryRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AddFinanceEntryRequest() {
    bandId_ = "";
    initiatorsBandId_ = "";
    initiatorsEmail_ = "";
    amount_ = "";
    description_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AddFinanceEntryRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.qsspy.grpc.finances.command.FinancesCommand.internal_static_AddFinanceEntryRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.qsspy.grpc.finances.command.FinancesCommand.internal_static_AddFinanceEntryRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.qsspy.grpc.finances.command.AddFinanceEntryRequest.class, com.qsspy.grpc.finances.command.AddFinanceEntryRequest.Builder.class);
  }

  public static final int BANDID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object bandId_ = "";
  /**
   * <code>string bandId = 1;</code>
   * @return The bandId.
   */
  @java.lang.Override
  public java.lang.String getBandId() {
    java.lang.Object ref = bandId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bandId_ = s;
      return s;
    }
  }
  /**
   * <code>string bandId = 1;</code>
   * @return The bytes for bandId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBandIdBytes() {
    java.lang.Object ref = bandId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bandId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INITIATORSBANDID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object initiatorsBandId_ = "";
  /**
   * <code>string initiatorsBandId = 2;</code>
   * @return The initiatorsBandId.
   */
  @java.lang.Override
  public java.lang.String getInitiatorsBandId() {
    java.lang.Object ref = initiatorsBandId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      initiatorsBandId_ = s;
      return s;
    }
  }
  /**
   * <code>string initiatorsBandId = 2;</code>
   * @return The bytes for initiatorsBandId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInitiatorsBandIdBytes() {
    java.lang.Object ref = initiatorsBandId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      initiatorsBandId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INITIATORSEMAIL_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object initiatorsEmail_ = "";
  /**
   * <code>string initiatorsEmail = 3;</code>
   * @return The initiatorsEmail.
   */
  @java.lang.Override
  public java.lang.String getInitiatorsEmail() {
    java.lang.Object ref = initiatorsEmail_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      initiatorsEmail_ = s;
      return s;
    }
  }
  /**
   * <code>string initiatorsEmail = 3;</code>
   * @return The bytes for initiatorsEmail.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInitiatorsEmailBytes() {
    java.lang.Object ref = initiatorsEmail_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      initiatorsEmail_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AMOUNT_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object amount_ = "";
  /**
   * <code>string amount = 4;</code>
   * @return The amount.
   */
  @java.lang.Override
  public java.lang.String getAmount() {
    java.lang.Object ref = amount_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      amount_ = s;
      return s;
    }
  }
  /**
   * <code>string amount = 4;</code>
   * @return The bytes for amount.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAmountBytes() {
    java.lang.Object ref = amount_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      amount_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object description_ = "";
  /**
   * <code>string description = 5;</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>string description = 5;</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISOUTCOME_FIELD_NUMBER = 6;
  private boolean isOutcome_ = false;
  /**
   * <code>bool isOutcome = 6;</code>
   * @return The isOutcome.
   */
  @java.lang.Override
  public boolean getIsOutcome() {
    return isOutcome_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bandId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, bandId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(initiatorsBandId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, initiatorsBandId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(initiatorsEmail_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, initiatorsEmail_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(amount_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, amount_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, description_);
    }
    if (isOutcome_ != false) {
      output.writeBool(6, isOutcome_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bandId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, bandId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(initiatorsBandId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, initiatorsBandId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(initiatorsEmail_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, initiatorsEmail_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(amount_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, amount_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, description_);
    }
    if (isOutcome_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, isOutcome_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.qsspy.grpc.finances.command.AddFinanceEntryRequest)) {
      return super.equals(obj);
    }
    com.qsspy.grpc.finances.command.AddFinanceEntryRequest other = (com.qsspy.grpc.finances.command.AddFinanceEntryRequest) obj;

    if (!getBandId()
        .equals(other.getBandId())) return false;
    if (!getInitiatorsBandId()
        .equals(other.getInitiatorsBandId())) return false;
    if (!getInitiatorsEmail()
        .equals(other.getInitiatorsEmail())) return false;
    if (!getAmount()
        .equals(other.getAmount())) return false;
    if (!getDescription()
        .equals(other.getDescription())) return false;
    if (getIsOutcome()
        != other.getIsOutcome()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BANDID_FIELD_NUMBER;
    hash = (53 * hash) + getBandId().hashCode();
    hash = (37 * hash) + INITIATORSBANDID_FIELD_NUMBER;
    hash = (53 * hash) + getInitiatorsBandId().hashCode();
    hash = (37 * hash) + INITIATORSEMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getInitiatorsEmail().hashCode();
    hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getAmount().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (37 * hash) + ISOUTCOME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsOutcome());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.qsspy.grpc.finances.command.AddFinanceEntryRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.qsspy.grpc.finances.command.AddFinanceEntryRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.qsspy.grpc.finances.command.AddFinanceEntryRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.qsspy.grpc.finances.command.AddFinanceEntryRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.qsspy.grpc.finances.command.AddFinanceEntryRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.qsspy.grpc.finances.command.AddFinanceEntryRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.qsspy.grpc.finances.command.AddFinanceEntryRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.qsspy.grpc.finances.command.AddFinanceEntryRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.qsspy.grpc.finances.command.AddFinanceEntryRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.qsspy.grpc.finances.command.AddFinanceEntryRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.qsspy.grpc.finances.command.AddFinanceEntryRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.qsspy.grpc.finances.command.AddFinanceEntryRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.qsspy.grpc.finances.command.AddFinanceEntryRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code AddFinanceEntryRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:AddFinanceEntryRequest)
      com.qsspy.grpc.finances.command.AddFinanceEntryRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qsspy.grpc.finances.command.FinancesCommand.internal_static_AddFinanceEntryRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qsspy.grpc.finances.command.FinancesCommand.internal_static_AddFinanceEntryRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qsspy.grpc.finances.command.AddFinanceEntryRequest.class, com.qsspy.grpc.finances.command.AddFinanceEntryRequest.Builder.class);
    }

    // Construct using com.qsspy.grpc.finances.command.AddFinanceEntryRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      bandId_ = "";
      initiatorsBandId_ = "";
      initiatorsEmail_ = "";
      amount_ = "";
      description_ = "";
      isOutcome_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.qsspy.grpc.finances.command.FinancesCommand.internal_static_AddFinanceEntryRequest_descriptor;
    }

    @java.lang.Override
    public com.qsspy.grpc.finances.command.AddFinanceEntryRequest getDefaultInstanceForType() {
      return com.qsspy.grpc.finances.command.AddFinanceEntryRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.qsspy.grpc.finances.command.AddFinanceEntryRequest build() {
      com.qsspy.grpc.finances.command.AddFinanceEntryRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.qsspy.grpc.finances.command.AddFinanceEntryRequest buildPartial() {
      com.qsspy.grpc.finances.command.AddFinanceEntryRequest result = new com.qsspy.grpc.finances.command.AddFinanceEntryRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.qsspy.grpc.finances.command.AddFinanceEntryRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.bandId_ = bandId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.initiatorsBandId_ = initiatorsBandId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.initiatorsEmail_ = initiatorsEmail_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.amount_ = amount_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.description_ = description_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.isOutcome_ = isOutcome_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.qsspy.grpc.finances.command.AddFinanceEntryRequest) {
        return mergeFrom((com.qsspy.grpc.finances.command.AddFinanceEntryRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.qsspy.grpc.finances.command.AddFinanceEntryRequest other) {
      if (other == com.qsspy.grpc.finances.command.AddFinanceEntryRequest.getDefaultInstance()) return this;
      if (!other.getBandId().isEmpty()) {
        bandId_ = other.bandId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getInitiatorsBandId().isEmpty()) {
        initiatorsBandId_ = other.initiatorsBandId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getInitiatorsEmail().isEmpty()) {
        initiatorsEmail_ = other.initiatorsEmail_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getAmount().isEmpty()) {
        amount_ = other.amount_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.getIsOutcome() != false) {
        setIsOutcome(other.getIsOutcome());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              bandId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              initiatorsBandId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              initiatorsEmail_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              amount_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              description_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 48: {
              isOutcome_ = input.readBool();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object bandId_ = "";
    /**
     * <code>string bandId = 1;</code>
     * @return The bandId.
     */
    public java.lang.String getBandId() {
      java.lang.Object ref = bandId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bandId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string bandId = 1;</code>
     * @return The bytes for bandId.
     */
    public com.google.protobuf.ByteString
        getBandIdBytes() {
      java.lang.Object ref = bandId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bandId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string bandId = 1;</code>
     * @param value The bandId to set.
     * @return This builder for chaining.
     */
    public Builder setBandId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      bandId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string bandId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearBandId() {
      bandId_ = getDefaultInstance().getBandId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string bandId = 1;</code>
     * @param value The bytes for bandId to set.
     * @return This builder for chaining.
     */
    public Builder setBandIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      bandId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object initiatorsBandId_ = "";
    /**
     * <code>string initiatorsBandId = 2;</code>
     * @return The initiatorsBandId.
     */
    public java.lang.String getInitiatorsBandId() {
      java.lang.Object ref = initiatorsBandId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        initiatorsBandId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string initiatorsBandId = 2;</code>
     * @return The bytes for initiatorsBandId.
     */
    public com.google.protobuf.ByteString
        getInitiatorsBandIdBytes() {
      java.lang.Object ref = initiatorsBandId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        initiatorsBandId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string initiatorsBandId = 2;</code>
     * @param value The initiatorsBandId to set.
     * @return This builder for chaining.
     */
    public Builder setInitiatorsBandId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      initiatorsBandId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string initiatorsBandId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearInitiatorsBandId() {
      initiatorsBandId_ = getDefaultInstance().getInitiatorsBandId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string initiatorsBandId = 2;</code>
     * @param value The bytes for initiatorsBandId to set.
     * @return This builder for chaining.
     */
    public Builder setInitiatorsBandIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      initiatorsBandId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object initiatorsEmail_ = "";
    /**
     * <code>string initiatorsEmail = 3;</code>
     * @return The initiatorsEmail.
     */
    public java.lang.String getInitiatorsEmail() {
      java.lang.Object ref = initiatorsEmail_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        initiatorsEmail_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string initiatorsEmail = 3;</code>
     * @return The bytes for initiatorsEmail.
     */
    public com.google.protobuf.ByteString
        getInitiatorsEmailBytes() {
      java.lang.Object ref = initiatorsEmail_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        initiatorsEmail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string initiatorsEmail = 3;</code>
     * @param value The initiatorsEmail to set.
     * @return This builder for chaining.
     */
    public Builder setInitiatorsEmail(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      initiatorsEmail_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string initiatorsEmail = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearInitiatorsEmail() {
      initiatorsEmail_ = getDefaultInstance().getInitiatorsEmail();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string initiatorsEmail = 3;</code>
     * @param value The bytes for initiatorsEmail to set.
     * @return This builder for chaining.
     */
    public Builder setInitiatorsEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      initiatorsEmail_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object amount_ = "";
    /**
     * <code>string amount = 4;</code>
     * @return The amount.
     */
    public java.lang.String getAmount() {
      java.lang.Object ref = amount_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        amount_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string amount = 4;</code>
     * @return The bytes for amount.
     */
    public com.google.protobuf.ByteString
        getAmountBytes() {
      java.lang.Object ref = amount_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        amount_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string amount = 4;</code>
     * @param value The amount to set.
     * @return This builder for chaining.
     */
    public Builder setAmount(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      amount_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string amount = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAmount() {
      amount_ = getDefaultInstance().getAmount();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string amount = 4;</code>
     * @param value The bytes for amount to set.
     * @return This builder for chaining.
     */
    public Builder setAmountBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      amount_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>string description = 5;</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string description = 5;</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string description = 5;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      description_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string description = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      description_ = getDefaultInstance().getDescription();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string description = 5;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      description_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private boolean isOutcome_ ;
    /**
     * <code>bool isOutcome = 6;</code>
     * @return The isOutcome.
     */
    @java.lang.Override
    public boolean getIsOutcome() {
      return isOutcome_;
    }
    /**
     * <code>bool isOutcome = 6;</code>
     * @param value The isOutcome to set.
     * @return This builder for chaining.
     */
    public Builder setIsOutcome(boolean value) {

      isOutcome_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>bool isOutcome = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsOutcome() {
      bitField0_ = (bitField0_ & ~0x00000020);
      isOutcome_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:AddFinanceEntryRequest)
  }

  // @@protoc_insertion_point(class_scope:AddFinanceEntryRequest)
  private static final com.qsspy.grpc.finances.command.AddFinanceEntryRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.qsspy.grpc.finances.command.AddFinanceEntryRequest();
  }

  public static com.qsspy.grpc.finances.command.AddFinanceEntryRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AddFinanceEntryRequest>
      PARSER = new com.google.protobuf.AbstractParser<AddFinanceEntryRequest>() {
    @java.lang.Override
    public AddFinanceEntryRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AddFinanceEntryRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AddFinanceEntryRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.qsspy.grpc.finances.command.AddFinanceEntryRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

