// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: finances-command.proto

package com.qsspy.grpc.finances.command;

public final class FinancesCommand {
  private FinancesCommand() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddFinanceEntryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddFinanceEntryRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026finances-command.proto\032\033google/protobu" +
      "f/empty.proto\"\223\001\n\026AddFinanceEntryRequest" +
      "\022\016\n\006bandId\030\001 \001(\t\022\030\n\020initiatorsBandId\030\002 \001" +
      "(\t\022\027\n\017initiatorsEmail\030\003 \001(\t\022\016\n\006amount\030\004 " +
      "\001(\t\022\023\n\013description\030\005 \001(\t\022\021\n\tisOutcome\030\006 " +
      "\001(\0102^\n\026FinancesCommandService\022D\n\017AddFina" +
      "nceEntry\022\027.AddFinanceEntryRequest\032\026.goog" +
      "le.protobuf.Empty\"\000B#\n\037com.qsspy.grpc.fi" +
      "nances.commandP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_AddFinanceEntryRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AddFinanceEntryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddFinanceEntryRequest_descriptor,
        new java.lang.String[] { "BandId", "InitiatorsBandId", "InitiatorsEmail", "Amount", "Description", "IsOutcome", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
