package com.qsspy.bands.infrastructure.dataview.bandmemberprivilegebybandiduserid;

import org.springframework.data.cassandra.repository.CassandraRepository;
import org.springframework.stereotype.Repository;

@Repository
interface BandMemberPrivilegeByBandIdUserIdCassandraRepository extends CassandraRepository<BandMemberPrivilegeByBandIdUserId, BandMemberPrivilegeByBandIdUserIdKey> {
}
